/**
 * deploy_fix_index_v2.js
 *
 * Reescreve index_meta.js completo com:
 * - Normalizacao @c.us no sender (Meta API envia sem sufixo)
 * - try/catch correto em onMessage e onPollResponse
 * - Handlers de botoes confirmar_ID / ausente_ID / lista_ID / adm_grp_ID
 */

var fs   = require('fs');
var BASE = '/home/appfutadmin/appfut';

var content = [
  "require('dotenv').config();",
  "var express = require('express');",
  "var db      = require('../database/connection');",
  "var { client }     = require('./whatsapp/metaClient');",
  "var { router: webhookRouter, setHandlers } = require('./whatsapp/webhook');",
  "var { processarComandoGrupo } = require('./commands/grupo');",
  "var { processarComandoAdmin }  = require('./commands/admin');",
  "var { ajudaPrivado }           = require('./commands/ajuda');",
  "var { confirmar, confirmarPartida } = require('./commands/confirmar');",
  "var { cancelar, cancelarPartida }   = require('./commands/cancelar');",
  "var { lista }                       = require('./commands/lista');",
  "var { adicionarAvulso, removerAvulso } = require('./commands/avulso');",
  "var { buscarGruposDoAdmin } = require('./utils/adminHelper');",
  "var { iniciarScheduler } = require('./scheduler');",
  "",
  "// dedup de mensagens",
  "var processadas = new Set();",
  "function dedup(id) {",
  "  if (processadas.has(id)) return false;",
  "  processadas.add(id);",
  "  setTimeout(function() { processadas.delete(id); }, 30 * 60 * 1000);",
  "  return true;",
  "}",
  "",
  "// sessoes admin (state machine)",
  "var sessoes = {};",
  "function getSession(s)       { return sessoes[s] || null; }",
  "function setSession(s, d)    { sessoes[s] = d; }",
  "function clearSession(s)     { delete sessoes[s]; }",
  "global._appfutSession = { getSession, setSession, clearSession };",
  "",
  "// -------- onMessage --------",
  "async function onMessage(message) {",
  "  try {",
  "    if (!message.sender || !dedup(message.id)) return;",
  "    var text       = (message.body || '').trim().toLowerCase();",
  "    var sender     = message.sender.id;",
  "    // Normaliza: Meta API envia sem @c.us, banco usa @c.us (padrao WPPConnect)",
  "    if (sender && !sender.includes('@')) sender = sender + '@c.us';",
  "    var senderName = message.sender.pushname || 'Jogador';",
  "",
  "    if (message.isGroupMsg) {",
  "      await processarComandoGrupo(client, message);",
  "      return;",
  "    }",
  "",
  "    // Auto-registro/atualizacao do jogador",
  "    await autoRegistrarJogador(sender, senderName);",
  "",
  "    // Admin via texto",
  "    if (text.startsWith('admin ') || text === 'admin') {",
  "      var cmdTexto = text === 'admin' ? 'admin ajuda' : text;",
  "      var cmdArgs  = cmdTexto.substring(6).trim().split(/\\s+/);",
  "      var cmdBase  = cmdArgs[0];",
  "      var grupoDep = ['criar','fechar','status','participantes','ativar','desativar','financeiro','pago'];",
  "",
  "      if (grupoDep.indexOf(cmdBase) !== -1) {",
  "        var adminGruposList = await buscarGruposDoAdmin(sender);",
  "        if (adminGruposList.length === 0) {",
  "          await client.sendText(message.from, 'Voc\u00ea n\u00e3o \u00e9 admin de nenhum grupo. \u26a0\ufe0f');",
  "          return;",
  "        }",
  "        if (adminGruposList.length > 1) {",
  "          var adminBtns = adminGruposList.slice(0, 3).map(function(g) {",
  "            return { id: 'adm_grp_' + g.id, title: g.nome.slice(0, 20) };",
  "          });",
  "          setSession(sender, { pendingAdminCmd: cmdTexto, step: 'select_grupo' });",
  "          await client.sendButtons(message.from, '\ud83d\udccb Qual grupo?', adminBtns);",
  "          return;",
  "        }",
  "        // Um grupo: define na sessao",
  "        setSession(sender, { adminGrupoId: adminGruposList[0].id });",
  "      }",
  "",
  "      await processarComandoAdmin(client, message, sender, cmdTexto);",
  "      if (getSession(sender) && getSession(sender).adminGrupoId) clearSession(sender);",
  "      return;",
  "    }",
  "",
  "    // Comandos jogador privado",
  "    switch (text) {",
  "      case 'ajuda':    await ajudaPrivado(client, message, sender); break;",
  "      case 'confirmar': await confirmar(client, message, sender, senderName); break;",
  "      case 'cancelar':  await cancelar(client, message, sender); break;",
  "      case 'lista':     await lista(client, message, sender); break;",
  "      default:",
  "        if (text.startsWith('avulso ')) { await adicionarAvulso(client, message, sender, text); }",
  "        else if (text.startsWith('remover avulso ')) { await removerAvulso(client, message, sender, text); }",
  "        break;",
  "    }",
  "  } catch(e) { console.error('[onMessage] Erro:', e); }",
  "}",
  "",
  "// Auto-registro: cadastra jogador na primeira mensagem e migra LID",
  "async function autoRegistrarJogador(sender, senderName) {",
  "  try {",
  "    var [existente] = await db.execute('SELECT id, nome FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "    if (existente.length > 0) {",
  "      if (senderName && senderName !== 'Jogador' && existente[0].nome !== senderName) {",
  "        await db.execute('UPDATE jogadores SET nome = ? WHERE id = ?', [senderName, existente[0].id]);",
  "      }",
  "      return;",
  "    }",
  "    // Tenta migrar registro LID pelo nome exato",
  "    if (senderName && senderName !== 'Jogador') {",
  "      var [lidRows] = await db.execute(",
  "        'SELECT id FROM jogadores WHERE nome = ? AND whatsapp_id LIKE \"%@lid\"',",
  "        [senderName]",
  "      );",
  "      if (lidRows.length === 1) {",
  "        await db.execute('UPDATE jogadores SET whatsapp_id = ? WHERE id = ?', [sender, lidRows[0].id]);",
  "        console.log('[AutoReg] Migrado LID -> real:', senderName, sender);",
  "        return;",
  "      }",
  "    }",
  "    // Cadastra novo jogador",
  "    var [result] = await db.execute(",
  "      'INSERT IGNORE INTO jogadores (whatsapp_id, nome) VALUES (?, ?)',",
  "      [sender, senderName]",
  "    );",
  "    if (result.insertId) {",
  "      var [grupos] = await db.execute(",
  "        'SELECT grupo_id, COUNT(*) as total FROM grupo_jogadores WHERE ativo = TRUE GROUP BY grupo_id ORDER BY total DESC LIMIT 1'",
  "      );",
  "      if (grupos.length > 0) {",
  "        await db.execute(",
  "          'INSERT IGNORE INTO grupo_jogadores (grupo_id, jogador_id) VALUES (?, ?)',",
  "          [grupos[0].grupo_id, result.insertId]",
  "        );",
  "        console.log('[AutoReg] Novo jogador:', senderName, sender, '-> grupo', grupos[0].grupo_id);",
  "      }",
  "    }",
  "  } catch(e) { console.error('[AutoReg] Erro:', e); }",
  "}",
  "",
  "// -------- onPollResponse --------",
  "async function onPollResponse(response, sender, opcao) {",
  "  try {",
  "    // Normaliza sender",
  "    if (sender && !sender.includes('@')) sender = sender + '@c.us';",
  "",
  "    var btnId = (response.selectedOptions && response.selectedOptions[0] && response.selectedOptions[0].id) || '';",
  "    var opcaoNorm = (opcao || '').toLowerCase().trim()",
  "      .normalize('NFD').replace(/[\\u0300-\\u036f]/g, '');",
  "",
  "    // Confirmar presenca em partida especifica (botao do lembrete/confirmar)",
  "    if (btnId.startsWith('confirmar_')) {",
  "      var chaveC = sender + btnId;",
  "      if (!dedup(chaveC)) return;",
  "      var partidaIdC = parseInt(btnId.replace('confirmar_', ''));",
  "      var [pRowC] = await db.execute(",
  "        'SELECT p.id, p.max_jogadores, p.data_partida, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim FROM partidas p JOIN grupos g ON p.grupo_id = g.id WHERE p.id = ?',",
  "        [partidaIdC]",
  "      );",
  "      if (pRowC.length === 0) return;",
  "      var [jC] = await db.execute('SELECT id, nome FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "      if (jC.length === 0) return;",
  "      await confirmarPartida(client, sender, jC[0].id, jC[0].nome, pRowC[0]);",
  "      return;",
  "    }",
  "",
  "    // Marcar ausente em partida especifica",
  "    if (btnId.startsWith('ausente_')) {",
  "      var chaveA = sender + btnId;",
  "      if (!dedup(chaveA)) return;",
  "      var partidaIdA = parseInt(btnId.replace('ausente_', ''));",
  "      var [pRowA] = await db.execute(",
  "        'SELECT p.id, p.max_jogadores, p.data_partida, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim FROM partidas p JOIN grupos g ON p.grupo_id = g.id WHERE p.id = ?',",
  "        [partidaIdA]",
  "      );",
  "      if (pRowA.length === 0) return;",
  "      var [jA] = await db.execute('SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "      if (jA.length === 0) return;",
  "      await cancelarPartida(client, sender, jA[0].id, pRowA[0]);",
  "      return;",
  "    }",
  "",
  "    // Ver lista de partida especifica",
  "    if (btnId.startsWith('lista_')) {",
  "      var chaveL = sender + btnId;",
  "      if (!dedup(chaveL)) return;",
  "      var partidaIdL = parseInt(btnId.replace('lista_', ''));",
  "      var [pRowL] = await db.execute(",
  "        'SELECT p.id, p.max_jogadores, p.data_partida, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim FROM partidas p JOIN grupos g ON p.grupo_id = g.id WHERE p.id = ?',",
  "        [partidaIdL]",
  "      );",
  "      if (pRowL.length === 0) return;",
  "      var { buscarDadosLista, montarLista } = require('./commands/confirmar');",
  "      var dadosL = await buscarDadosLista(pRowL[0]);",
  "      await client.sendText(sender, montarLista(dadosL, pRowL[0]));",
  "      return;",
  "    }",
  "",
  "    // Selecao de grupo admin",
  "    if (btnId.startsWith('adm_grp_')) {",
  "      var grupoIdSel = parseInt(btnId.replace('adm_grp_', ''));",
  "      var sessAdm = getSession(sender);",
  "      if (sessAdm && sessAdm.pendingAdminCmd) {",
  "        setSession(sender, { adminGrupoId: grupoIdSel });",
  "        var msgFakeAdm = { from: sender, sender: { id: sender, pushname: 'Admin' } };",
  "        await processarComandoAdmin(client, msgFakeAdm, sender, sessAdm.pendingAdminCmd);",
  "        clearSession(sender);",
  "      }",
  "      return;",
  "    }",
  "",
  "    // Botoes de lembrete legado (titulo normalizado)",
  "    if (opcaoNorm === 'confirmar presenca') {",
  "      var chaveCP = sender + (response.id || '') + opcao;",
  "      if (!dedup(chaveCP)) return;",
  "      var senderNameCP = 'Jogador';",
  "      try {",
  "        var [jCP] = await db.execute('SELECT nome FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "        if (jCP.length > 0) senderNameCP = jCP[0].nome;",
  "      } catch(e2) {}",
  "      var msgFakeCP = { from: sender, sender: { id: sender, pushname: senderNameCP } };",
  "      await confirmar(client, msgFakeCP, sender, senderNameCP);",
  "      return;",
  "    }",
  "    if (opcaoNorm === 'estarei ausente') {",
  "      var chaveEA = sender + (response.id || '') + opcao;",
  "      if (!dedup(chaveEA)) return;",
  "      var msgFakeEA = { from: sender, sender: { id: sender, pushname: 'Jogador' } };",
  "      await cancelar(client, msgFakeEA, sender);",
  "      return;",
  "    }",
  "",
  "    // AdminPoll",
  "    var { processarAdminPoll } = require('./commands/adminPoll');",
  "    if (getSession(sender) && getSession(sender).step !== 'select_grupo') {",
  "      await processarAdminPoll(client, response, sender, opcao);",
  "      return;",
  "    }",
  "    var chave3 = sender + (response.id || '') + opcao;",
  "    if (!dedup(chave3)) return;",
  "    await processarAdminPoll(client, response, sender, opcao);",
  "  } catch(e) { console.error('[onPollResponse] Erro:', e); }",
  "}",
  "",
  "async function onParticipantsChanged(event) {",
  "  try { console.log('[Participants] Evento:', JSON.stringify(event)); }",
  "  catch(e) { console.error('[onParticipantsChanged] Erro:', e); }",
  "}",
  "",
  "// -------- servidor Express --------",
  "function start() {",
  "  var app  = express();",
  "  var PORT = process.env.PORT || 3000;",
  "  app.use(express.json());",
  "  setHandlers({ onMessage, onPollResponse, onParticipantsChanged });",
  "  app.use('/', webhookRouter);",
  "  app.get('/health', function(req, res) { res.json({ status: 'ok', ts: new Date().toISOString() }); });",
  "  app.listen(PORT, function() {",
  "    console.log('AppFut Bot (Meta API) rodando na porta ' + PORT);",
  "    console.log('Phone Number ID:', process.env.META_PHONE_NUMBER_ID || '(nao configurado)');",
  "  });",
  "  iniciarScheduler(client);",
  "  console.log('Scheduler iniciado.');",
  "}",
  "",
  "start();"
].join('\n');

fs.writeFileSync(BASE + '/src/bot/index_meta.js', content);
console.log('[OK] index_meta.js reescrito (v2 com @c.us)');
console.log('\nReinicie: pm2 restart appfut-meta --update-env');
