/**
 * deploy_lista_autoshow.js
 *
 * Adiciona exibicao automatica da lista apos confirmar e cancelar.
 * Ordem: mensagem de confirmacao/cancelamento + lista logo abaixo.
 */

var fs = require('fs');
var path = require('path');
var BASE = '/home/appfutadmin/appfut';

// ============================================================
// PATCH confirmar.js
// ============================================================

var confirmarPath = path.join(BASE, 'src/bot/commands/confirmar.js');
var confirmarContent = fs.readFileSync(confirmarPath, 'utf8');

var newConfirmar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "",
  "async function confirmar(client, message, sender, senderName) {",
  "  const limite = verificarRateLimit(sender, 'confirmar');",
  "  if (!limite.permitido) return;",
  "",
  "  await delay();",
  "",
  "  await db.execute(",
  "    'INSERT IGNORE INTO jogadores (whatsapp_id, nome) VALUES (?, ?)',",
  "    [sender, senderName]",
  "  );",
  "  const [jogador] = await db.execute(",
  "    'SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]",
  "  );",
  "",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta'",
  "       AND gj.jogador_id = ?",
  "       AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC",
  "     LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (partidas.length === 0) {",
  "    await client.sendText(message.from, 'Não há nenhum jogo aberto no momento. ⚠️');",
  "    return;",
  "  }",
  "",
  "  const partida = partidas[0];",
  "",
  "  const [contagem] = await db.execute(",
  "    'SELECT COUNT(*) as total FROM presencas WHERE partida_id = ?', [partida.id]",
  "  );",
  "",
  "  if (contagem[0].total >= partida.max_jogadores) {",
  "    await client.sendText(message.from, 'O jogo já está lotado (' + partida.max_jogadores + ' jogadores). 😕');",
  "    return;",
  "  }",
  "",
  "  const [result] = await db.execute(",
  "    'INSERT IGNORE INTO presencas (partida_id, jogador_id) VALUES (?, ?)',",
  "    [partida.id, jogador[0].id]",
  "  );",
  "",
  "  if (result.affectedRows === 0) {",
  "    await client.sendText(message.from, 'Você já está confirmado! ✅');",
  "  } else {",
  "    const vaga = contagem[0].total + 1;",
  "    await client.sendText(message.from,",
  "      '✅ Presença confirmada, ' + senderName + '!\\n' +",
  "      '📋 Vaga ' + vaga + '/' + partida.max_jogadores + '\\n' +",
  "      '⚽ Grupo: ' + partida.grupo_nome",
  "    );",
  "  }",
  "",
  "  // Envia lista automaticamente apos confirmacao",
  "  await delay();",
  "  await enviarListaResumida(client, message.from, partida.id, partida.max_jogadores, partida.grupo_nome, partida.grupo_id, jogador[0].id);",
  "}",
  "",
  "async function enviarListaResumida(client, to, partidaId, maxJogadores, grupoNome, grupoId, jogadorId) {",
  "  try {",
  "    const [confirmados] = await db.execute(",
  "      `SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? ORDER BY pr.confirmado_em ASC`,",
  "      [partidaId]",
  "    );",
  "    const [ausentes] = await db.execute(",
  "      `SELECT j.nome FROM grupo_jogadores gj JOIN jogadores j ON gj.jogador_id = j.id",
  "       WHERE gj.grupo_id = ? AND gj.ativo = TRUE",
  "       AND gj.jogador_id NOT IN (SELECT jogador_id FROM presencas WHERE partida_id = ?)`,",
  "      [grupoId, partidaId]",
  "    );",
  "    const [avulsos] = await db.execute(",
  "      'SELECT nome FROM avulsos WHERE partida_id = ? ORDER BY nome', [partidaId]",
  "    );",
  "",
  "    var total = confirmados.length + avulsos.length;",
  "    var texto = '\\n📋 *Lista atualizada — ' + total + '/' + maxJogadores + '*\\n\\n';",
  "",
  "    if (confirmados.length > 0) {",
  "      texto += '✅ *Confirmados (' + confirmados.length + '):*\\n';",
  "      confirmados.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "    if (avulsos.length > 0) {",
  "      texto += '\\n👤 *Avulsos (' + avulsos.length + '):*\\n';",
  "      avulsos.forEach(function(a, i) { texto += (i + 1) + '. ' + a.nome + '\\n'; });",
  "    }",
  "    if (ausentes.length > 0) {",
  "      texto += '\\n❌ *Pendentes (' + ausentes.length + '):*\\n';",
  "      ausentes.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "",
  "    await client.sendText(to, texto);",
  "  } catch(e) {",
  "    console.error('[Lista auto] Erro:', e);",
  "  }",
  "}",
  "",
  "module.exports = { confirmar };"
].join('\n');

fs.writeFileSync(confirmarPath, newConfirmar);
console.log('[OK] confirmar.js atualizado');

// ============================================================
// PATCH cancelar.js
// ============================================================

var cancelarPath = path.join(BASE, 'src/bot/commands/cancelar.js');

var newCancelar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "",
  "async function cancelar(client, message, sender) {",
  "  const limite = verificarRateLimit(sender, 'cancelar');",
  "  if (!limite.permitido) return;",
  "",
  "  await delay();",
  "",
  "  const [jogador] = await db.execute(",
  "    'SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]",
  "  );",
  "",
  "  if (jogador.length === 0) {",
  "    await client.sendText(message.from, 'Você não está cadastrado. ⚠️');",
  "    return;",
  "  }",
  "",
  "  // Busca partida antes de deletar para ter os dados da lista",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta'",
  "       AND gj.jogador_id = ?",
  "       AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  const [result] = await db.execute(",
  "    `DELETE pr FROM presencas pr",
  "     JOIN partidas p ON pr.partida_id = p.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = p.grupo_id AND gj.jogador_id = pr.jogador_id",
  "     WHERE pr.jogador_id = ?",
  "       AND p.status = 'aberta'",
  "       AND gj.ativo = TRUE`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (result.affectedRows === 0) {",
  "    await client.sendText(message.from, 'Você não tinha presença confirmada. 🤷');",
  "    return;",
  "  }",
  "",
  "  await client.sendText(message.from, 'Presença cancelada. Até a próxima! 👋');",
  "",
  "  // Envia lista automaticamente apos cancelamento",
  "  if (partidas.length > 0) {",
  "    await delay();",
  "    await enviarListaResumida(client, message.from, partidas[0].id, partidas[0].max_jogadores, partidas[0].grupo_nome, partidas[0].grupo_id, jogador[0].id);",
  "  }",
  "}",
  "",
  "async function enviarListaResumida(client, to, partidaId, maxJogadores, grupoNome, grupoId, jogadorId) {",
  "  try {",
  "    const [confirmados] = await db.execute(",
  "      `SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? ORDER BY pr.confirmado_em ASC`,",
  "      [partidaId]",
  "    );",
  "    const [ausentes] = await db.execute(",
  "      `SELECT j.nome FROM grupo_jogadores gj JOIN jogadores j ON gj.jogador_id = j.id",
  "       WHERE gj.grupo_id = ? AND gj.ativo = TRUE",
  "       AND gj.jogador_id NOT IN (SELECT jogador_id FROM presencas WHERE partida_id = ?)`,",
  "      [grupoId, partidaId]",
  "    );",
  "    const [avulsos] = await db.execute(",
  "      'SELECT nome FROM avulsos WHERE partida_id = ? ORDER BY nome', [partidaId]",
  "    );",
  "",
  "    var total = confirmados.length + avulsos.length;",
  "    var texto = '\\n📋 *Lista atualizada — ' + total + '/' + maxJogadores + '*\\n\\n';",
  "",
  "    if (confirmados.length > 0) {",
  "      texto += '✅ *Confirmados (' + confirmados.length + '):*\\n';",
  "      confirmados.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "    if (avulsos.length > 0) {",
  "      texto += '\\n👤 *Avulsos (' + avulsos.length + '):*\\n';",
  "      avulsos.forEach(function(a, i) { texto += (i + 1) + '. ' + a.nome + '\\n'; });",
  "    }",
  "    if (ausentes.length > 0) {",
  "      texto += '\\n❌ *Pendentes (' + ausentes.length + '):*\\n';",
  "      ausentes.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "",
  "    await client.sendText(to, texto);",
  "  } catch(e) {",
  "    console.error('[Lista auto] Erro:', e);",
  "  }",
  "}",
  "",
  "module.exports = { cancelar };"
].join('\n');

fs.writeFileSync(cancelarPath, newCancelar);
console.log('[OK] cancelar.js atualizado');

console.log('\nReinicie: pm2 restart appfut-meta --update-env');
