/**
 * deploy_avulso_lista.js
 *
 * Atualiza avulso.js: apos adicionar/remover avulso, exibe lista completa
 * em mensagem unica (mesmo padrao do confirmar/cancelar).
 */

var fs   = require('fs');
var path = require('path');
var BASE = '/home/appfutadmin/appfut';

var newAvulso = [
  "var db = require('../../database/connection');",
  "var { delay } = require('../utils/rateLimit');",
  "var { buscarDadosLista, montarLista } = require('./confirmar');",
  "",
  "async function adicionarAvulso(client, message, sender, textoCompleto) {",
  "  await delay();",
  "",
  "  var nome = textoCompleto.substring(7).trim();",
  "  if (!nome || nome.length < 2) {",
  "    await client.sendText(message.from, 'Use: *avulso Nome do Jogador*\\nExemplo: avulso Joao Silva');",
  "    return;",
  "  }",
  "",
  "  var [jogador] = await db.execute('SELECT id, nome FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "  if (jogador.length === 0) {",
  "    await client.sendText(message.from, 'Voce nao esta cadastrado em nenhum grupo.');",
  "    return;",
  "  }",
  "",
  "  var [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, p.data_partida, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta' AND gj.jogador_id = ? AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (partidas.length === 0) {",
  "    await client.sendText(message.from, 'Nao ha jogo aberto no momento.');",
  "    return;",
  "  }",
  "",
  "  var partida = partidas[0];",
  "",
  "  var [presenca] = await db.execute(",
  "    'SELECT id FROM presencas WHERE partida_id = ? AND jogador_id = ? AND status = \\'confirmado\\'',",
  "    [partida.id, jogador[0].id]",
  "  );",
  "  if (presenca.length === 0) {",
  "    await client.sendText(message.from, 'Voce precisa confirmar sua presenca primeiro antes de adicionar um avulso.');",
  "    return;",
  "  }",
  "",
  "  var [totalConfirmados] = await db.execute(",
  "    'SELECT COUNT(*) as total FROM presencas WHERE partida_id = ? AND status = \\'confirmado\\'', [partida.id]",
  "  );",
  "  var [totalAvulsos] = await db.execute(",
  "    'SELECT COUNT(*) as total FROM avulsos WHERE partida_id = ?', [partida.id]",
  "  );",
  "  var totalGeral = totalConfirmados[0].total + totalAvulsos[0].total;",
  "",
  "  if (totalGeral >= partida.max_jogadores) {",
  "    await client.sendText(message.from, 'O jogo ja esta lotado (' + partida.max_jogadores + ' vagas).');",
  "    return;",
  "  }",
  "",
  "  await db.execute(",
  "    'INSERT INTO avulsos (partida_id, nome, adicionado_por) VALUES (?, ?, ?)',",
  "    [partida.id, nome, jogador[0].id]",
  "  );",
  "",
  "  try {",
  "    var dados = await buscarDadosLista(partida);",
  "    var lista = montarLista(dados, partida);",
  "    await client.sendText(message.from, '\u2705 *' + nome + '* adicionado como avulso!\\n\\n' + lista);",
  "  } catch(e) {",
  "    console.error('[avulso] Erro lista:', e);",
  "    await client.sendText(message.from, '\u2705 *' + nome + '* adicionado como avulso!');",
  "  }",
  "}",
  "",
  "async function removerAvulso(client, message, sender, textoCompleto) {",
  "  await delay();",
  "",
  "  var nome = textoCompleto.substring(15).trim();",
  "  if (!nome || nome.length < 2) {",
  "    await client.sendText(message.from, 'Use: *remover avulso Nome do Jogador*');",
  "    return;",
  "  }",
  "",
  "  var [jogador] = await db.execute('SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "  if (jogador.length === 0) return;",
  "",
  "  var [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, p.data_partida, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta' AND gj.jogador_id = ? AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  var [result] = await db.execute(",
  "    `DELETE a FROM avulsos a",
  "     JOIN partidas p ON a.partida_id = p.id",
  "     WHERE a.adicionado_por = ? AND a.nome = ? AND p.status = 'aberta'`,",
  "    [jogador[0].id, nome]",
  "  );",
  "",
  "  if (result.affectedRows === 0) {",
  "    await client.sendText(message.from, 'Avulso \"' + nome + '\" nao encontrado ou voce nao foi quem adicionou.');",
  "    return;",
  "  }",
  "",
  "  if (partidas.length > 0) {",
  "    try {",
  "      var dados = await buscarDadosLista(partidas[0]);",
  "      var lista = montarLista(dados, partidas[0]);",
  "      await client.sendText(message.from, '\u274c *' + nome + '* removido da lista.\\n\\n' + lista);",
  "      return;",
  "    } catch(e) {",
  "      console.error('[remover avulso] Erro lista:', e);",
  "    }",
  "  }",
  "  await client.sendText(message.from, '\u274c *' + nome + '* removido da lista.');",
  "}",
  "",
  "module.exports = { adicionarAvulso, removerAvulso };"
].join('\n');

fs.writeFileSync(path.join(BASE, 'src/bot/commands/avulso.js'), newAvulso);
console.log('[OK] avulso.js atualizado');
console.log('\nReinicie: pm2 restart appfut-meta --update-env');
