/**
 * deploy_fix_confirmar_cancelar.js
 *
 * Restaura textos originais de confirmar/cancelar e mantem lista automatica.
 */

var fs = require('fs');
var BASE = '/home/appfutadmin/appfut';

// ============================================================
// confirmar.js
// ============================================================

var newConfirmar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "",
  "async function confirmar(client, message, sender, senderName) {",
  "  const limite = verificarRateLimit(sender, 'confirmar');",
  "  if (!limite.permitido) return;",
  "",
  "  await delay();",
  "",
  "  await db.execute(",
  "    'INSERT IGNORE INTO jogadores (whatsapp_id, nome) VALUES (?, ?)',",
  "    [sender, senderName]",
  "  );",
  "  const [jogador] = await db.execute(",
  "    'SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]",
  "  );",
  "",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta'",
  "       AND gj.jogador_id = ?",
  "       AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC",
  "     LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (partidas.length === 0) {",
  "    await client.sendText(message.from, 'N\u00e3o h\u00e1 nenhum jogo aberto no momento. \u26a0\ufe0f');",
  "    return;",
  "  }",
  "",
  "  const partida = partidas[0];",
  "",
  "  const [contagem] = await db.execute(",
  "    'SELECT COUNT(*) as total FROM presencas WHERE partida_id = ?', [partida.id]",
  "  );",
  "",
  "  if (contagem[0].total >= partida.max_jogadores) {",
  "    await client.sendText(message.from, 'O jogo j\u00e1 est\u00e1 lotado (' + partida.max_jogadores + ' jogadores). \ud83d\ude15');",
  "    return;",
  "  }",
  "",
  "  const [result] = await db.execute(",
  "    'INSERT IGNORE INTO presencas (partida_id, jogador_id) VALUES (?, ?)',",
  "    [partida.id, jogador[0].id]",
  "  );",
  "",
  "  if (result.affectedRows === 0) {",
  "    await client.sendText(message.from, 'Voc\u00ea j\u00e1 est\u00e1 confirmado! \u2705');",
  "  } else {",
  "    const vaga = contagem[0].total + 1;",
  "    await client.sendText(message.from,",
  "      '\u2705 Presen\u00e7a confirmada, ' + senderName + '!\\n' +",
  "      '\ud83d\udccb Vaga ' + vaga + '/' + partida.max_jogadores + '\\n' +",
  "      '\u26bd Grupo: ' + partida.grupo_nome",
  "    );",
  "  }",
  "",
  "  // Lista automatica apos confirmacao",
  "  await delay();",
  "  await enviarListaResumida(client, message.from, partida.id, partida.max_jogadores, partida.grupo_nome, partida.grupo_id);",
  "}",
  "",
  "async function enviarListaResumida(client, to, partidaId, maxJogadores, grupoNome, grupoId) {",
  "  try {",
  "    const [confirmados] = await db.execute(",
  "      'SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? ORDER BY pr.confirmado_em ASC',",
  "      [partidaId]",
  "    );",
  "    const [ausentes] = await db.execute(",
  "      `SELECT j.nome FROM grupo_jogadores gj JOIN jogadores j ON gj.jogador_id = j.id",
  "       WHERE gj.grupo_id = ? AND gj.ativo = TRUE",
  "       AND gj.jogador_id NOT IN (SELECT jogador_id FROM presencas WHERE partida_id = ?)`,",
  "      [grupoId, partidaId]",
  "    );",
  "    const [avulsos] = await db.execute(",
  "      'SELECT nome FROM avulsos WHERE partida_id = ? ORDER BY nome', [partidaId]",
  "    );",
  "",
  "    var total = confirmados.length + avulsos.length;",
  "    var texto = '\ud83d\udccb *Lista atualizada \u2014 ' + total + '/' + maxJogadores + '*\\n\\n';",
  "",
  "    if (confirmados.length > 0) {",
  "      texto += '\u2705 *Confirmados (' + confirmados.length + '):*\\n';",
  "      confirmados.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "    if (avulsos.length > 0) {",
  "      texto += '\\n\ud83d\udc64 *Avulsos (' + avulsos.length + '):*\\n';",
  "      avulsos.forEach(function(a, i) { texto += (i + 1) + '. ' + a.nome + '\\n'; });",
  "    }",
  "    if (ausentes.length > 0) {",
  "      texto += '\\n\u274c *Pendentes (' + ausentes.length + '):*\\n';",
  "      ausentes.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "",
  "    await client.sendText(to, texto);",
  "  } catch(e) {",
  "    console.error('[Lista auto] Erro:', e);",
  "  }",
  "}",
  "",
  "module.exports = { confirmar };"
].join('\n');

fs.writeFileSync(BASE + '/src/bot/commands/confirmar.js', newConfirmar);
console.log('[OK] confirmar.js restaurado');

// ============================================================
// cancelar.js
// ============================================================

var newCancelar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "",
  "async function cancelar(client, message, sender) {",
  "  const limite = verificarRateLimit(sender, 'cancelar');",
  "  if (!limite.permitido) return;",
  "",
  "  await delay();",
  "",
  "  const [jogador] = await db.execute(",
  "    'SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]",
  "  );",
  "",
  "  if (jogador.length === 0) {",
  "    await client.sendText(message.from, 'Voc\u00ea n\u00e3o est\u00e1 cadastrado. \u26a0\ufe0f');",
  "    return;",
  "  }",
  "",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id",
  "     FROM partidas p",
  "     JOIN grupos g ON p.grupo_id = g.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta'",
  "       AND gj.jogador_id = ?",
  "       AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  const [result] = await db.execute(",
  "    `DELETE pr FROM presencas pr",
  "     JOIN partidas p ON pr.partida_id = p.id",
  "     JOIN grupo_jogadores gj ON gj.grupo_id = p.grupo_id AND gj.jogador_id = pr.jogador_id",
  "     WHERE pr.jogador_id = ?",
  "       AND p.status = 'aberta'",
  "       AND gj.ativo = TRUE`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (result.affectedRows === 0) {",
  "    await client.sendText(message.from, 'Voc\u00ea n\u00e3o tinha presen\u00e7a confirmada. \ud83e\udd37');",
  "    return;",
  "  }",
  "",
  "  await client.sendText(message.from, 'Presen\u00e7a cancelada. At\u00e9 a pr\u00f3xima! \ud83d\udc4b');",
  "",
  "  // Lista automatica apos cancelamento",
  "  if (partidas.length > 0) {",
  "    await delay();",
  "    await enviarListaResumida(client, message.from, partidas[0].id, partidas[0].max_jogadores, partidas[0].grupo_nome, partidas[0].grupo_id);",
  "  }",
  "}",
  "",
  "async function enviarListaResumida(client, to, partidaId, maxJogadores, grupoNome, grupoId) {",
  "  try {",
  "    const [confirmados] = await db.execute(",
  "      'SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? ORDER BY pr.confirmado_em ASC',",
  "      [partidaId]",
  "    );",
  "    const [ausentes] = await db.execute(",
  "      `SELECT j.nome FROM grupo_jogadores gj JOIN jogadores j ON gj.jogador_id = j.id",
  "       WHERE gj.grupo_id = ? AND gj.ativo = TRUE",
  "       AND gj.jogador_id NOT IN (SELECT jogador_id FROM presencas WHERE partida_id = ?)`,",
  "      [grupoId, partidaId]",
  "    );",
  "    const [avulsos] = await db.execute(",
  "      'SELECT nome FROM avulsos WHERE partida_id = ? ORDER BY nome', [partidaId]",
  "    );",
  "",
  "    var total = confirmados.length + avulsos.length;",
  "    var texto = '\ud83d\udccb *Lista atualizada \u2014 ' + total + '/' + maxJogadores + '*\\n\\n';",
  "",
  "    if (confirmados.length > 0) {",
  "      texto += '\u2705 *Confirmados (' + confirmados.length + '):*\\n';",
  "      confirmados.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "    if (avulsos.length > 0) {",
  "      texto += '\\n\ud83d\udc64 *Avulsos (' + avulsos.length + '):*\\n';",
  "      avulsos.forEach(function(a, i) { texto += (i + 1) + '. ' + a.nome + '\\n'; });",
  "    }",
  "    if (ausentes.length > 0) {",
  "      texto += '\\n\u274c *Pendentes (' + ausentes.length + '):*\\n';",
  "      ausentes.forEach(function(j, i) { texto += (i + 1) + '. ' + j.nome + '\\n'; });",
  "    }",
  "",
  "    await client.sendText(to, texto);",
  "  } catch(e) {",
  "    console.error('[Lista auto] Erro:', e);",
  "  }",
  "}",
  "",
  "module.exports = { cancelar };"
].join('\n');

fs.writeFileSync(BASE + '/src/bot/commands/cancelar.js', newCancelar);
console.log('[OK] cancelar.js restaurado');

console.log('\nReinicie: pm2 restart appfut-meta --update-env');
