/**
 * deploy_msg_unica.js
 *
 * Mescla confirmacao/cancelamento + lista em UMA unica mensagem.
 * Remove o segundo sendText — a lista ja mostra o jogador no campo correto.
 */

var fs   = require('fs');
var path = require('path');
var BASE = '/home/appfutadmin/appfut';

// ============================================================
// confirmar.js — mensagem unica
// ============================================================

var newConfirmar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "",
  "async function confirmar(client, message, sender, senderName) {",
  "  const limite = verificarRateLimit(sender, 'confirmar');",
  "  if (!limite.permitido) return;",
  "  await delay();",
  "",
  "  await db.execute('INSERT IGNORE INTO jogadores (whatsapp_id, nome) VALUES (?, ?)', [sender, senderName]);",
  "  const [jogador] = await db.execute('SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim, p.data_partida",
  "     FROM partidas p JOIN grupos g ON p.grupo_id = g.id JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta' AND gj.jogador_id = ? AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (partidas.length === 0) {",
  "    await client.sendText(message.from, 'N\u00e3o h\u00e1 nenhum jogo aberto no momento. \u26a0\ufe0f');",
  "    return;",
  "  }",
  "",
  "  const partida = partidas[0];",
  "  const [contagem] = await db.execute(",
  "    'SELECT COUNT(*) as total FROM presencas WHERE partida_id = ? AND status = \\'confirmado\\'', [partida.id]",
  "  );",
  "",
  "  if (contagem[0].total >= partida.max_jogadores) {",
  "    await client.sendText(message.from, 'O jogo j\u00e1 est\u00e1 lotado (' + partida.max_jogadores + ' jogadores). \ud83d\ude15');",
  "    return;",
  "  }",
  "",
  "  await db.execute(",
  "    'INSERT INTO presencas (partida_id, jogador_id, status) VALUES (?, ?, \\'confirmado\\') ON DUPLICATE KEY UPDATE status = \\'confirmado\\'',",
  "    [partida.id, jogador[0].id]",
  "  );",
  "",
  "  try {",
  "    var dados = await buscarDadosLista(partida);",
  "    var lista = montarLista(dados, partida);",
  "    await client.sendText(message.from, '\u2705 Presen\u00e7a confirmada, ' + senderName + '!\\n\\n' + lista);",
  "  } catch(e) {",
  "    console.error('[confirmar] Erro lista:', e);",
  "    await client.sendText(message.from, '\u2705 Presen\u00e7a confirmada, ' + senderName + '!');",
  "  }",
  "}",
  "",
  "async function buscarDadosLista(partida) {",
  "  const [confirmados] = await db.execute(",
  "    'SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? AND pr.status = \\'confirmado\\' ORDER BY pr.confirmado_em ASC',",
  "    [partida.id]",
  "  );",
  "  const [ausentes] = await db.execute(",
  "    'SELECT j.nome FROM presencas pr JOIN jogadores j ON pr.jogador_id = j.id WHERE pr.partida_id = ? AND pr.status = \\'ausente\\' ORDER BY j.nome ASC',",
  "    [partida.id]",
  "  );",
  "  const [duvida] = await db.execute(",
  "    `SELECT j.nome FROM grupo_jogadores gj JOIN jogadores j ON gj.jogador_id = j.id",
  "     WHERE gj.grupo_id = ? AND gj.ativo = TRUE",
  "     AND gj.jogador_id NOT IN (SELECT jogador_id FROM presencas WHERE partida_id = ?)`,",
  "    [partida.grupo_id, partida.id]",
  "  );",
  "  const [avulsos] = await db.execute(",
  "    'SELECT nome FROM avulsos WHERE partida_id = ? ORDER BY nome', [partida.id]",
  "  );",
  "  return { confirmados, ausentes, duvida, avulsos };",
  "}",
  "",
  "function montarLista(dados, partida) {",
  "  var { confirmados, ausentes, duvida, avulsos } = dados;",
  "  var total = confirmados.length + avulsos.length;",
  "",
  "  var dataP = new Date(partida.data_partida);",
  "  var dataF = dataP.toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: '2-digit' });",
  "  var hi = partida.horario_inicio ? String(partida.horario_inicio).replace(/:00$/, '') : '';",
  "  var hf = partida.horario_fim    ? String(partida.horario_fim).replace(/:00$/, '')    : '';",
  "  var horario = hi ? hi + ' - ' + hf : '';",
  "",
  "  var txt = '\u26bd *' + partida.grupo_nome + '*\\n';",
  "  txt += '\ud83d\udcc5 ' + dataF + '\\n';",
  "  if (horario) txt += '\u23f0 ' + horario + '\\n';",
  "  txt += '\ud83d\udccb ' + total + '/' + partida.max_jogadores + '\\n\\n';",
  "",
  "  txt += '\u2705 *Confirmados (' + confirmados.length + '):*\\n';",
  "  if (confirmados.length === 0) { txt += 'Nenhum confirmado ainda\\n'; }",
  "  else { confirmados.forEach(function(j) { txt += '- ' + j.nome + '\\n'; }); }",
  "",
  "  txt += '\\n\u274c *Ausentes (' + ausentes.length + '):*\\n';",
  "  if (ausentes.length === 0) { txt += 'Nenhum ausente\\n'; }",
  "  else { ausentes.forEach(function(j) { txt += '- ' + j.nome + '\\n'; }); }",
  "",
  "  txt += '\\n\u2753 *D\u00favida (' + duvida.length + '):*\\n';",
  "  if (duvida.length === 0) { txt += 'Todos responderam\\n'; }",
  "  else { duvida.forEach(function(j) { txt += '- ' + j.nome + '\\n'; }); }",
  "",
  "  txt += '\\n\ud83d\udd38 *Avulsos (' + avulsos.length + '):*\\n';",
  "  if (avulsos.length === 0) { txt += 'Nenhum avulso\\n'; }",
  "  else { avulsos.forEach(function(a) { txt += '- ' + a.nome + '\\n'; }); }",
  "",
  "  txt += '\\n\ud83d\udca1 Caso precise ficar ausente, digite *cancelar*';",
  "  txt += '\\n\ud83d\udca1 Para trazer algu\u00e9m: *avulso Nome*';",
  "  return txt;",
  "}",
  "",
  "module.exports = { confirmar, buscarDadosLista, montarLista };"
].join('\n');

fs.writeFileSync(path.join(BASE, 'src/bot/commands/confirmar.js'), newConfirmar);
console.log('[OK] confirmar.js');

// ============================================================
// cancelar.js — mensagem unica
// ============================================================

var newCancelar = [
  "const db = require('../../database/connection');",
  "const { verificarRateLimit, delay } = require('../utils/rateLimit');",
  "const { buscarDadosLista, montarLista } = require('./confirmar');",
  "",
  "async function cancelar(client, message, sender) {",
  "  const limite = verificarRateLimit(sender, 'cancelar');",
  "  if (!limite.permitido) return;",
  "  await delay();",
  "",
  "  const [jogador] = await db.execute('SELECT id FROM jogadores WHERE whatsapp_id = ?', [sender]);",
  "  if (jogador.length === 0) {",
  "    await client.sendText(message.from, 'Voc\u00ea n\u00e3o est\u00e1 cadastrado. \u26a0\ufe0f');",
  "    return;",
  "  }",
  "",
  "  const [partidas] = await db.execute(",
  "    `SELECT p.id, p.max_jogadores, g.nome as grupo_nome, g.id as grupo_id, g.horario_inicio, g.horario_fim, p.data_partida",
  "     FROM partidas p JOIN grupos g ON p.grupo_id = g.id JOIN grupo_jogadores gj ON gj.grupo_id = g.id",
  "     WHERE p.status = 'aberta' AND gj.jogador_id = ? AND gj.ativo = TRUE",
  "     ORDER BY p.data_partida ASC LIMIT 1`,",
  "    [jogador[0].id]",
  "  );",
  "",
  "  if (partidas.length === 0) {",
  "    await client.sendText(message.from, 'N\u00e3o h\u00e1 jogo aberto no momento. \u26a0\ufe0f');",
  "    return;",
  "  }",
  "",
  "  const partida = partidas[0];",
  "",
  "  await db.execute(",
  "    'INSERT INTO presencas (partida_id, jogador_id, status) VALUES (?, ?, \\'ausente\\') ON DUPLICATE KEY UPDATE status = \\'ausente\\'',",
  "    [partida.id, jogador[0].id]",
  "  );",
  "",
  "  try {",
  "    var dados = await buscarDadosLista(partida);",
  "    var lista = montarLista(dados, partida);",
  "    await client.sendText(message.from, 'Presen\u00e7a cancelada. At\u00e9 a pr\u00f3xima! \ud83d\udc4b\\n\\n' + lista);",
  "  } catch(e) {",
  "    console.error('[cancelar] Erro lista:', e);",
  "    await client.sendText(message.from, 'Presen\u00e7a cancelada. At\u00e9 a pr\u00f3xima! \ud83d\udc4b');",
  "  }",
  "}",
  "",
  "module.exports = { cancelar };"
].join('\n');

fs.writeFileSync(path.join(BASE, 'src/bot/commands/cancelar.js'), newCancelar);
console.log('[OK] cancelar.js');

console.log('\nReinicie: pm2 restart appfut-meta --update-env');
